[package]
name = "euler-math"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["gmborjasb <@gmborjasb>"]
license = "MIT"
description = "Modern and robust Math Olympiad problems and exams."
repository = "https://github.com/gmborjasb/euler-math"
keywords = ["math", "olympiad", "exam", "contest", "problem-solving", "theorion"]
categories = ["report", "components"]
disciplines = ["mathematics", "education"]
compiler = "0.13.0"
exclude = ["examples", ".github"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"